# Minimalistic config file for features testing
root: mixins/source
destination: mixins/dest
name: r-backup
exclude:
  patterns:
    - ^exclude
    - shouldnt-be-copied\\.txt
  paths:
    - truc
include:
  - one

